/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { forwardRef } from "react";
import * as THREE from "three";
import Text from "../Text";

export const AWS = forwardRef<THREE.Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/models/web_logos/aws.glb");
  return (
    <group {...props} scale={0.5} ref={ref}>
      <Text content="aws" size={0.06} position={[0.025, -0.17, 0]} />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Curve004 as THREE.Mesh).geometry}
        material={materials["SVGMat.004"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Curve004_1 as THREE.Mesh).geometry}
        material={materials["SVGMat.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Curve004_2 as THREE.Mesh).geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
});

AWS.displayName = "AWS";

useGLTF.preload("/models/web_logos/aws.glb");
