/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { forwardRef } from "react";
import * as THREE from "three";
import Text from "../Text";

export const Azure = forwardRef<THREE.Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/models/web_logos/azure.glb");
  return (
    <group scale={0.1} {...props} ref={ref} dispose={null}>
      <Text content="Azure" size={0.3} position={[0.56, -0.3, 0]} />
      <group scale={10.817}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve050 as THREE.Mesh).geometry}
          material={materials["SVGMat.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve050_1 as THREE.Mesh).geometry}
          material={materials["SVGMat.056"]}
        />
      </group>
    </group>
  );
});

Azure.displayName = "Azure";

useGLTF.preload("/models/web_logos/azure.glb");
