/*
Auto-generated by: https://dockerhub.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { forwardRef } from "react";
import * as THREE from "three";
import Text from "../Text";

export const Docker = forwardRef<THREE.Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/models/web_logos/docker.glb");
  return (
    <group scale={0.1} {...props} ref={ref} dispose={null}>
      <Text content="Docker" position={[-0.67, -0.35, 0]} />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Curve021 as THREE.Mesh).geometry}
        material={materials["SVGMat.051"]}
      />
    </group>
  );
});

Docker.displayName = "Docker";

useGLTF.preload("/models/web_logos/docker.glb");
