/*
Auto-generated by: https://expresshub.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { forwardRef } from "react";
import * as THREE from "three";
import Text from "../Text";

export const Express = forwardRef<THREE.Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/models/web_logos/express.glb");
  return (
    <group scale={0.1} {...props} ref={ref} dispose={null}>
      <Text content="Express.js" position={[-0.22, -0.9, 0]} />
      <group scale={87.183}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve011 as THREE.Mesh).geometry}
          material={materials["SVGMat.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve011_1 as THREE.Mesh).geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
});

Express.displayName = "Express";

useGLTF.preload("/models/web_logos/express.glb");
