/*
Auto-generated by: https://firebasehub.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { forwardRef } from "react";
import * as THREE from "three";
import Text from "../Text";

export const Firebase = forwardRef<THREE.Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/models/web_logos/firebase.glb");
  return (
    <group scale={0.1} {...props} ref={ref} dispose={null}>
      <Text content="Firebase" position={[-0.2, -1.05, 0]} />
      <group scale={4.651}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve046 as THREE.Mesh).geometry}
          material={materials["SVGMat.052"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve046_1 as THREE.Mesh).geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve046_2 as THREE.Mesh).geometry}
          material={materials["SVGMat.053"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve046_3 as THREE.Mesh).geometry}
          material={materials["SVGMat.054"]}
        />
      </group>
    </group>
  );
});

Firebase.displayName = "Firebase";

useGLTF.preload("/models/web_logos/firebase.glb");
