/*
Auto-generated by: https://javascripthub.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { forwardRef } from "react";
import * as THREE from "three";
import Text from "../Text";

export const Javascript = forwardRef<THREE.Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/models/web_logos/javascript.glb");
  return (
    <group scale={0.1} {...props} ref={ref} dispose={null}>
      <Text content="JavaScript" position={[-0.53, -0.5, 0]} />
      <group scale={5.913}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve008 as THREE.Mesh).geometry}
          material={materials["SVGMat.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve008_1 as THREE.Mesh).geometry}
          material={materials["Material.002"]}
        />
      </group>
    </group>
  );
});

Javascript.displayName = "Javascript";

useGLTF.preload("/models/web_logos/javascript.glb");
