/*
Auto-generated by: https://jesthub.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { forwardRef } from "react";
import * as THREE from "three";
import Text from "../Text";

export const Jest = forwardRef<THREE.Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/models/web_logos/jest.glb");
  return (
    <group scale={0.1} {...props} ref={ref} dispose={null}>
      <Text content="Jest" position={[0.33, -0.82, 0]} />
      <group scale={5.789}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve044 as THREE.Mesh).geometry}
          material={materials["SVGMat.050"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve044_1 as THREE.Mesh).geometry}
          material={materials["Material.005"]}
        />
      </group>
    </group>
  );
});

Jest.displayName = "Jest";

useGLTF.preload("/models/web_logos/jest.glb");
