/*
Auto-generated by: https://mongodbhub.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { forwardRef } from "react";
import * as THREE from "three";
import Text from "../Text";

export const MongoDB = forwardRef<THREE.Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/models/web_logos/mongodb.glb");
  return (
    <group scale={0.1} {...props} ref={ref} dispose={null}>
      <Text content="MongoDB" position={[-0.89, -0.4, 0]} />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Cube008 as THREE.Mesh).geometry}
        material={materials["Material.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Cube008_1 as THREE.Mesh).geometry}
        material={materials["SVGMat.028"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Cube008_2 as THREE.Mesh).geometry}
        material={materials["SVGMat.029"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Cube008_3 as THREE.Mesh).geometry}
        material={materials["SVGMat.030"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Cube008_4 as THREE.Mesh).geometry}
        material={materials["SVGMat.031"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Cube008_5 as THREE.Mesh).geometry}
        material={materials["SVGMat.032"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Cube008_6 as THREE.Mesh).geometry}
        material={materials["SVGMat.033"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Cube008_7 as THREE.Mesh).geometry}
        material={materials["SVGMat.034"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Cube008_8 as THREE.Mesh).geometry}
        material={materials["SVGMat.035"]}
      />
    </group>
  );
});

MongoDB.displayName = "MongoDB";

useGLTF.preload("/models/web_logos/mongodb.glb");
