/*
Auto-generated by: https://reacthub.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { forwardRef } from "react";
import * as THREE from "three";
import Text from "../Text";

export const React = forwardRef<THREE.Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/models/web_logos/react.glb");
  return (
    <group scale={0.1} {...props} ref={ref} dispose={null}>
      <Text content="React" position={[-0.5, -0.4, 0]} />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Curve as THREE.Mesh).geometry}
        material={materials["SVGMat.001"]}
        scale={9.179}
      />
    </group>
  );
});

React.displayName = "React";

useGLTF.preload("/models/web_logos/react.glb");
