/*
Auto-generated by: https://socketiohub.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { forwardRef } from "react";
import * as THREE from "three";
import Text from "../Text";

export const SocketIO = forwardRef<THREE.Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/models/web_logos/socket_io.glb");
  return (
    <group scale={0.1} {...props} ref={ref} dispose={null}>
      <Text content="Socket.IO" position={[-0.2, -0.9, 0]} />
      <group scale={5.558}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve042 as THREE.Mesh).geometry}
          material={materials["SVGMat.047"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve042_1 as THREE.Mesh).geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
});

SocketIO.displayName = "SocketIO";

useGLTF.preload("/models/web_logos/socket_io.glb");
