/*
Auto-generated by: https://typescripthub.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { forwardRef } from "react";
import * as THREE from "three";
import Text from "../Text";

export const Typescript = forwardRef<THREE.Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/models/web_logos/typescript.glb");
  return (
    <group scale={0.1} {...props} ref={ref} dispose={null}>
      <Text content="TypeScript" position={[-0.5, -0.5, 0]} />
      <group scale={5.81}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve007 as THREE.Mesh).geometry}
          material={materials["SVGMat.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve007_1 as THREE.Mesh).geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
});

Typescript.displayName = "Typescript";

useGLTF.preload("/models/web_logos/typescript.glb");
