/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function BlackPlanet() {
  const { nodes, materials } = useGLTF("/black_planet.glb");
  return (
    <group dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Sphere007_Material002_0001 as THREE.Mesh).geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.793}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Sphere007_Material001_0002 as THREE.Mesh).geometry}
          material={materials["Material.001"]}
          scale={1.036}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Sphere008_Material002_0001 as THREE.Mesh).geometry}
            material={materials["Material.002"]}
            scale={1.034}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Sphere007_Material001_0003 as THREE.Mesh).geometry}
          material={materials["Material.001"]}
          scale={1.036}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/black_planet.glb");
