/*
Auto-generated by: https://nodehub.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { forwardRef } from "react";
import * as THREE from "three";
import Text from "../Text";

export const Node = forwardRef<THREE.Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/models/web_logos/node.glb");
  return (
    <group scale={0.1} {...props} ref={ref} dispose={null}>
      <Text content="Node.js" position={[0.65, -0.4, 0]} />
      <group scale={11.189}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve010 as THREE.Mesh).geometry}
          material={materials["SVGMat.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve010_1 as THREE.Mesh).geometry}
          material={materials["SVGMat.012"]}
        />
      </group>
    </group>
  );
});

Node.displayName = "Node";

useGLTF.preload("/models/web_logos/node.glb");
