/*
Auto-generated by: https://redishub.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { forwardRef } from "react";
import * as THREE from "three";
import Text from "../Text";

export const Redis = forwardRef<THREE.Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/models/web_logos/redis.glb");
  return (
    <group scale={0.1} {...props} ref={ref} dispose={null}>
      <Text content="Redis" position={[0.15, -0.9, 0]} />
      <group scale={5.409}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve041 as THREE.Mesh).geometry}
          material={materials["SVGMat.046"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve041_1 as THREE.Mesh).geometry}
          material={materials["Material.004"]}
        />
      </group>
    </group>
  );
});

Redis.displayName = "Redis";

useGLTF.preload("/models/web_logos/redis.glb");
