/*
Auto-generated by: https://htmlhub.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { forwardRef } from "react";
import * as THREE from "three";
import Text from "../Text";

export const HTML = forwardRef<THREE.Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/models/web_logos/html.glb");
  return (
    <group scale={0.1} {...props} ref={ref} dispose={null}>
      <Text content="HTML" position={[0.33, -0.5, 0]} />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Curve032 as THREE.Mesh).geometry}
        material={materials["SVGMat.067"]}
        scale={7.336}
      />
    </group>
  );
});

HTML.displayName = "HTML";

useGLTF.preload("/models/web_logos/html.glb");
