/*
Auto-generated by: https://rabbitmqhub.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { forwardRef } from "react";
import * as THREE from "three";
import Text from "../Text";

export const RabbitMQ = forwardRef<THREE.Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/models/web_logos/rabbit_mq.glb");
  return (
    <group scale={0.1} {...props} ref={ref} dispose={null}>
      <Text content="RabbitMQ" position={[-0.43, -1.05, 0]} />
      <group scale={4.366}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve043 as THREE.Mesh).geometry}
          material={materials["SVGMat.049"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve043_1 as THREE.Mesh).geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
});

RabbitMQ.displayName = "RabbitMQ";

useGLTF.preload("/models/web_logos/rabbit_mq.glb");
